id: P008150
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90030
  title: རྔ་བ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  volumes:
    5fffda82378e45759ff8d6887cafb725:
      image_group_id: I1PD90112
      title: ''
      volume_number: 1
      total_pages: 800
ebook_metadata:
  title: རྔ་བ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  sku: P008150
  cover: cover.jpg
  layers:
  - pagination
