id: P008150
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90030
  title: རྔ་བ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  volumes:
    7a7252817302458c8ad297dc4fd822ef:
      image_group_id: I1PD90112
      title: Volume 1 of a ba xian zhi
      volume_number: 1
      total_pages: 800
      base_file: v001.txt
ebook_metadata:
  title: རྔ་བ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  sku: P008150
  cover: cover.jpg
  layers:
  - pagination
