id: P008150
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:44.065771
source_metadata:
  id: bdr:W1PD90030
  title: རྔ་བ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  volumes:
    7a7252817302458c8ad297dc4fd822ef:
      image_group_id: I1PD90112
      title: Volume 1 of a ba xian zhi
      volume_number: 1
      total_pages: 800
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
